### ISSUE TITLE
Login isn't working

### ISSUE THREAD

**Issue by stevesolanki77** [LamTechConsult/obizr#40]
![dsfsadfsadfa](https://cloud.githubusercontent.com/assets/8438275/22700092/6fccd69c-ed7f-11e6-9bda-9491cf5cc83c.PNG)
the login isn't working even in incognito.
the same 401 error is showing up.

please check this.

**Comment by stevesolanki77** [comment]
![err](https://cloud.githubusercontent.com/assets/8438275/22700184/c4c50930-ed7f-11e6-910f-4a0896225c95.PNG)

there is bug too as you can see from the app.controller.js lines, the same code is being executed twice.

**Comment by click2tman** [comment]
What command are you using the run the app? I use ionic serve and can login and work without issues. I am uploading a video to show you. make you checkout the right branch

**Comment by stevesolanki77** [comment]
![capture](https://cloud.githubusercontent.com/assets/8438275/22707743/cc27183e-ed99-11e6-8a5b-5ec2934d8ef7.PNG)


i was using " ionic serve --address localhost "

if using " ionic serve " . it gives the above errors.

if i use lcoalhost as the address, the address in the address bar is localhost:8100/
else it is http://192.168.0.10:8100/

**Comment by click2tman** [comment]
See this video. I am able to work without issue. https://youtu.be/7nWJEkwDp9M

**Comment by click2tman** [comment]
localhost is fine. Can call me and share your screen with me to see your project setup.

**Comment by stevesolanki77** [comment]
it's working now.
